name: daily-test

on:
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: npm install

      - name: lint
        run: npm run lint

      - name: tsc
        run: npm run tsc

      - name: test
        run: npm test

      - name: build
        run: npm run build

      - name: compile
        run: npm run compile
